// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.4
// source: user/account.proto

package user

import (
	common "github.com/biny-go/eagproto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAccountRequest) Reset() {
	*x = SaveAccountRequest{}
	mi := &file_user_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAccountRequest) ProtoMessage() {}

func (x *SaveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAccountRequest.ProtoReflect.Descriptor instead.
func (*SaveAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{0}
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_user_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{1}
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_user_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{2}
}

type ListAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountRequest) Reset() {
	*x = ListAccountRequest{}
	mi := &file_user_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRequest) ProtoMessage() {}

func (x *ListAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRequest.ProtoReflect.Descriptor instead.
func (*ListAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{3}
}

type AccountPOList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AccountPO           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPOList) Reset() {
	*x = AccountPOList{}
	mi := &file_user_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPOList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPOList) ProtoMessage() {}

func (x *AccountPOList) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPOList.ProtoReflect.Descriptor instead.
func (*AccountPOList) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountPOList) GetItems() []*AccountPO {
	if x != nil {
		return x.Items
	}
	return nil
}

type AccountPO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SYS_ID        string                 `protobuf:"bytes,1,opt,name=SYS_ID,json=SYSID,proto3" json:"SYS_ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPO) Reset() {
	*x = AccountPO{}
	mi := &file_user_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPO) ProtoMessage() {}

func (x *AccountPO) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPO.ProtoReflect.Descriptor instead.
func (*AccountPO) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{5}
}

func (x *AccountPO) GetSYS_ID() string {
	if x != nil {
		return x.SYS_ID
	}
	return ""
}

func (x *AccountPO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountPO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_user_account_proto protoreflect.FileDescriptor

const file_user_account_proto_rawDesc = "" +
	"\n" +
	"\x12user/account.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\"\x14\n" +
	"\x12SaveAccountRequest\"\x16\n" +
	"\x14DeleteAccountRequest\"\x13\n" +
	"\x11GetAccountRequest\"\x14\n" +
	"\x12ListAccountRequest\"6\n" +
	"\rAccountPOList\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.user.AccountPOR\x05items\"L\n" +
	"\tAccountPO\x12\x15\n" +
	"\x06SYS_ID\x18\x01 \x01(\tR\x05SYSID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email2\xd7\x02\n" +
	"\aAccount\x12P\n" +
	"\vSaveAccount\x12\x18.user.SaveAccountRequest\x1a\x12.common.BaseResult\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/account\x12Q\n" +
	"\rDeleteAccount\x12\x1a.user.DeleteAccountRequest\x1a\x12.common.BaseResult\"\x10\x82\xd3\xe4\x93\x02\n" +
	"*\b/account\x12K\n" +
	"\n" +
	"GetAccount\x12\x17.user.GetAccountRequest\x1a\x12.common.BaseResult\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/account\x12Z\n" +
	"\vListAccount\x12\x18.user.ListAccountRequest\x1a\x17.common.BaseResultArray\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/account/listB'Z%github.com/biny-go/eagproto/user;userb\x06proto3"

var (
	file_user_account_proto_rawDescOnce sync.Once
	file_user_account_proto_rawDescData []byte
)

func file_user_account_proto_rawDescGZIP() []byte {
	file_user_account_proto_rawDescOnce.Do(func() {
		file_user_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_account_proto_rawDesc), len(file_user_account_proto_rawDesc)))
	})
	return file_user_account_proto_rawDescData
}

var file_user_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_account_proto_goTypes = []any{
	(*SaveAccountRequest)(nil),     // 0: user.SaveAccountRequest
	(*DeleteAccountRequest)(nil),   // 1: user.DeleteAccountRequest
	(*GetAccountRequest)(nil),      // 2: user.GetAccountRequest
	(*ListAccountRequest)(nil),     // 3: user.ListAccountRequest
	(*AccountPOList)(nil),          // 4: user.AccountPOList
	(*AccountPO)(nil),              // 5: user.AccountPO
	(*common.BaseResult)(nil),      // 6: common.BaseResult
	(*common.BaseResultArray)(nil), // 7: common.BaseResultArray
}
var file_user_account_proto_depIdxs = []int32{
	5, // 0: user.AccountPOList.items:type_name -> user.AccountPO
	0, // 1: user.Account.SaveAccount:input_type -> user.SaveAccountRequest
	1, // 2: user.Account.DeleteAccount:input_type -> user.DeleteAccountRequest
	2, // 3: user.Account.GetAccount:input_type -> user.GetAccountRequest
	3, // 4: user.Account.ListAccount:input_type -> user.ListAccountRequest
	6, // 5: user.Account.SaveAccount:output_type -> common.BaseResult
	6, // 6: user.Account.DeleteAccount:output_type -> common.BaseResult
	6, // 7: user.Account.GetAccount:output_type -> common.BaseResult
	7, // 8: user.Account.ListAccount:output_type -> common.BaseResultArray
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_account_proto_init() }
func file_user_account_proto_init() {
	if File_user_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_account_proto_rawDesc), len(file_user_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_account_proto_goTypes,
		DependencyIndexes: file_user_account_proto_depIdxs,
		MessageInfos:      file_user_account_proto_msgTypes,
	}.Build()
	File_user_account_proto = out.File
	file_user_account_proto_goTypes = nil
	file_user_account_proto_depIdxs = nil
}
