// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.4
// source: user/hello.proto

package user

import (
	common "github.com/biny-go/eagproto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHelloRequest) Reset() {
	*x = SaveHelloRequest{}
	mi := &file_user_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHelloRequest) ProtoMessage() {}

func (x *SaveHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHelloRequest.ProtoReflect.Descriptor instead.
func (*SaveHelloRequest) Descriptor() ([]byte, []int) {
	return file_user_hello_proto_rawDescGZIP(), []int{0}
}

type DeleteHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHelloRequest) Reset() {
	*x = DeleteHelloRequest{}
	mi := &file_user_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelloRequest) ProtoMessage() {}

func (x *DeleteHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelloRequest.ProtoReflect.Descriptor instead.
func (*DeleteHelloRequest) Descriptor() ([]byte, []int) {
	return file_user_hello_proto_rawDescGZIP(), []int{1}
}

type GetHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelloRequest) Reset() {
	*x = GetHelloRequest{}
	mi := &file_user_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloRequest) ProtoMessage() {}

func (x *GetHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloRequest.ProtoReflect.Descriptor instead.
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return file_user_hello_proto_rawDescGZIP(), []int{2}
}

type ListHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelloRequest) Reset() {
	*x = ListHelloRequest{}
	mi := &file_user_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelloRequest) ProtoMessage() {}

func (x *ListHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelloRequest.ProtoReflect.Descriptor instead.
func (*ListHelloRequest) Descriptor() ([]byte, []int) {
	return file_user_hello_proto_rawDescGZIP(), []int{3}
}

type HelloPOList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HelloPO             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloPOList) Reset() {
	*x = HelloPOList{}
	mi := &file_user_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloPOList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloPOList) ProtoMessage() {}

func (x *HelloPOList) ProtoReflect() protoreflect.Message {
	mi := &file_user_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloPOList.ProtoReflect.Descriptor instead.
func (*HelloPOList) Descriptor() ([]byte, []int) {
	return file_user_hello_proto_rawDescGZIP(), []int{4}
}

func (x *HelloPOList) GetItems() []*HelloPO {
	if x != nil {
		return x.Items
	}
	return nil
}

type HelloPO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SYS_ID        string                 `protobuf:"bytes,1,opt,name=SYS_ID,json=SYSID,proto3" json:"SYS_ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloPO) Reset() {
	*x = HelloPO{}
	mi := &file_user_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloPO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloPO) ProtoMessage() {}

func (x *HelloPO) ProtoReflect() protoreflect.Message {
	mi := &file_user_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloPO.ProtoReflect.Descriptor instead.
func (*HelloPO) Descriptor() ([]byte, []int) {
	return file_user_hello_proto_rawDescGZIP(), []int{5}
}

func (x *HelloPO) GetSYS_ID() string {
	if x != nil {
		return x.SYS_ID
	}
	return ""
}

var File_user_hello_proto protoreflect.FileDescriptor

const file_user_hello_proto_rawDesc = "" +
	"\n" +
	"\x10user/hello.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\"\x12\n" +
	"\x10SaveHelloRequest\"\x14\n" +
	"\x12DeleteHelloRequest\"\x11\n" +
	"\x0fGetHelloRequest\"\x12\n" +
	"\x10ListHelloRequest\"2\n" +
	"\vHelloPOList\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.user.HelloPOR\x05items\" \n" +
	"\aHelloPO\x12\x15\n" +
	"\x06SYS_ID\x18\x01 \x01(\tR\x05SYSID2\xbd\x02\n" +
	"\x05Hello\x12J\n" +
	"\tSaveHello\x12\x16.user.SaveHelloRequest\x1a\x12.common.BaseResult\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/hello\x12K\n" +
	"\vDeleteHello\x12\x18.user.DeleteHelloRequest\x1a\x12.common.BaseResult\"\x0e\x82\xd3\xe4\x93\x02\b*\x06/hello\x12E\n" +
	"\bGetHello\x12\x15.user.GetHelloRequest\x1a\x12.common.BaseResult\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/hello\x12T\n" +
	"\tListHello\x12\x16.user.ListHelloRequest\x1a\x17.common.BaseResultArray\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/hello/listB'Z%github.com/biny-go/eagproto/user;userb\x06proto3"

var (
	file_user_hello_proto_rawDescOnce sync.Once
	file_user_hello_proto_rawDescData []byte
)

func file_user_hello_proto_rawDescGZIP() []byte {
	file_user_hello_proto_rawDescOnce.Do(func() {
		file_user_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_hello_proto_rawDesc), len(file_user_hello_proto_rawDesc)))
	})
	return file_user_hello_proto_rawDescData
}

var file_user_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_hello_proto_goTypes = []any{
	(*SaveHelloRequest)(nil),       // 0: user.SaveHelloRequest
	(*DeleteHelloRequest)(nil),     // 1: user.DeleteHelloRequest
	(*GetHelloRequest)(nil),        // 2: user.GetHelloRequest
	(*ListHelloRequest)(nil),       // 3: user.ListHelloRequest
	(*HelloPOList)(nil),            // 4: user.HelloPOList
	(*HelloPO)(nil),                // 5: user.HelloPO
	(*common.BaseResult)(nil),      // 6: common.BaseResult
	(*common.BaseResultArray)(nil), // 7: common.BaseResultArray
}
var file_user_hello_proto_depIdxs = []int32{
	5, // 0: user.HelloPOList.items:type_name -> user.HelloPO
	0, // 1: user.Hello.SaveHello:input_type -> user.SaveHelloRequest
	1, // 2: user.Hello.DeleteHello:input_type -> user.DeleteHelloRequest
	2, // 3: user.Hello.GetHello:input_type -> user.GetHelloRequest
	3, // 4: user.Hello.ListHello:input_type -> user.ListHelloRequest
	6, // 5: user.Hello.SaveHello:output_type -> common.BaseResult
	6, // 6: user.Hello.DeleteHello:output_type -> common.BaseResult
	6, // 7: user.Hello.GetHello:output_type -> common.BaseResult
	7, // 8: user.Hello.ListHello:output_type -> common.BaseResultArray
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_hello_proto_init() }
func file_user_hello_proto_init() {
	if File_user_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_hello_proto_rawDesc), len(file_user_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_hello_proto_goTypes,
		DependencyIndexes: file_user_hello_proto_depIdxs,
		MessageInfos:      file_user_hello_proto_msgTypes,
	}.Build()
	File_user_hello_proto = out.File
	file_user_hello_proto_goTypes = nil
	file_user_hello_proto_depIdxs = nil
}
